CLIENTE/client-contacts/config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :sessions, only: [:new, :create, :destroy]
  resources :contacts, only: [:index, :update, :destroy] do
    delete 'delete_phone/:id(.:format)', to: 'phones#destroy', as: 'delete_phone'
    post 'create_phone(.:format)' => "phones#create", as: 'create_phone'
  end
  resources :users, except: [:show,:index]
end

CLIENTE/client-contacts/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

CLIENTE/client-contacts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :web_default #variables que se inician por defecto

  private
  def web_default
    @api_url="http://localhost:3000"
  end
end

CLIENTE/client-contacts/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    ms=HTTParty.get(@api_url+"/user/contacts.json", headers: {"Authorization" => "Token token=\"#{session[:token]}\""})
    @body = JSON.parse(ms.body)
  end
  def update
    values={contact: {name: params["contact"]["name"],
              surname: params["contact"]["surname"],
              phone: params["contact"]["phone"],
              email: params["contact"]["email"]
    }}
    ms=HTTParty.put(@api_url+"/user/update_contact/#{params["id"]}.json",  body: values ,headers: {"Authorization" => "Token token=\"#{session[:token]}\""})
    redirect_to contacts_path , notice: "Contacto actualizado: #{ms.inspect} "
  end
  def destroy
    ms=HTTParty.delete(@api_url+"/user/delete_contact/#{params["id"]}.json", headers: {"Authorization" => "Token token=\"#{session[:token]}\""})
    redirect_to contacts_path , notice: "Contacto eliminado: #{ms.inspect} "
  end
end

CLIENTE/client-contacts/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

CLIENTE/client-contacts/app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def create
    #curl -H "Authorization: Token token=tUsFpXULLYL7LNzwcK88FYW7" -F "phone[number]=666 555 444"  http://localhost:3000/user/contact/1/create_phone.json > result.json
    values={phone: {number: params["phone"]["number"] }}
    ms=HTTParty.post(@api_url+"/user/contact/#{params[:contact_id]}/create_phone.json",  body: values ,headers: {"Authorization" => "Token token=\"#{session[:token]}\""})
    redirect_to contacts_path , notice: "Telf añadido: #{ms.inspect} "
  end
  def destroy
    ms=HTTParty.delete(@api_url+"/user/contact/#{params[:contact_id]}/delete_phone/#{params[:id]}.json", headers: {"Authorization" => "Token token=\"#{session[:token]}\""})
    redirect_to contacts_path , notice: "Telf eliminado: #{ms.inspect} "
  end
end

CLIENTE/client-contacts/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  def create
    values={email: params[:email] , password: params[:password]}
    ms=HTTParty.post("http://localhost:3000/login.json", body: values )
    body = JSON.parse(ms.body)
    session[:token]=body["token"]
    redirect_to root_path, notice: "Identicado con token #{body["token"]}"

  end
  def destroy
    session["token"]=nil
    redirect_to root_path, notice: "Cerraste la sesión"
  end
end

CLIENTE/client-contacts/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    ms=HTTParty.get(@api_url+"/user/show_user_by_token.json", headers: {"Authorization" => "Token token=\"#{session[:token]}\""})
    @body = JSON.parse(ms.body)
    #binding.pry
  end

  def update
    #curl -H "Authorization: Token token=tUsFpXULLYL7LNzwcK88FYW7" -X PUT --data "user[name]=ErSevilla&user[surname]=Burbujita&user[phone]=666122312&user[email]=LaSalle@salle.com&user[password]=1234567" http://localhost:3000/user/update_myself.json > result.json
    values={user: {name: params["name"],
                   surname: ["surname"],
                   phone: ["phone"],
                   email: ["email"],
                   email: ["password"]
    }}
    ms=HTTParty.put(@api_url+"/user/update_myself.json", body: values, headers: {"Authorization" => "Token token=\"#{session[:token]}\""})
    redirect_to edit_user_path(session[:token]), notice: "Usuario actualizado: #{ms.inspect}"
  end

  def new

  end

  def create

  end

  def destroy

  end
end

CLIENTE/client-contacts/app/helpers/application_helper.rb
module ApplicationHelper
end

CLIENTE/client-contacts/app/helpers/contacts_helper.rb
module ContactsHelper
end

CLIENTE/client-contacts/app/helpers/home_helper.rb
module HomeHelper
end

CLIENTE/client-contacts/app/helpers/phones_helper.rb
module PhonesHelper
end

CLIENTE/client-contacts/app/helpers/sessions_helper.rb
module SessionsHelper
end

CLIENTE/client-contacts/app/helpers/users_helper.rb
module UsersHelper
end

CLIENTE/client-contacts/app/views/contacts/index.html.erb
<table class="table table-bordered table-striped table-hover table-condensed table-responsive">
  <thead>
  <tr>
    <th>NOMBRE</th>
    <th>APELLIDOS</th>
    <th>TLF PRINCIPAL</th>
    <th>EMAIL</th>
    <th>TIPO</th>
    <th>AVATAR</th>
    <th>OTROS TELF</th>
    <th>ACCIONES</th>
  </tr>
  </thead>
  <tbody>
  <% for item in @body %>
      <tr>
        <td><%= item["name"].to_s %></td>
        <td><%= item["surname"].to_s %></td>
        <td><%= item["phone"].to_s %></td>
        <td><%= item["email"].to_s %></td>
        <td><%= item["type"].to_s %></td>
        <td><%= image_tag(@api_url+item["avatar"].to_s) %></td>
        <td>
          <% for phone in item["phones"] %>
              <%= phone["number"].to_s %><br/> <%= link_to 'Eliminar teléfono', contact_delete_phone_path(item["id"],phone["id"]),  method: :delete %><br/><br/><br/><br/>
          <% end %>
        </td>
        <td>

          <%= link_to 'Eliminar contacto',  contact_path(item["id"]),  method: :delete %><br/><br/>
          <button type="button" class="" data-toggle="modal" data-target="#editContact<%= item["id"] %>">
            Editar contacto
          </button>
          <br/><br/>

          <button type="button" class="" data-toggle="modal" data-target="#newPhone<%= item["id"] %>">
            Añadir tlf
          </button><br/><br/>
        </td>
      </tr>

      <!-- Modal editar contacto-->
      <div class="modal fade" id="editContact<%= item["id"] %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Editar(<%= item["id"] %>): <%= item["name"].to_s %> <%= item["surname"].to_s %></h4>
            </div>
            <div class="modal-body">
              <%= form_for(:contact, url:  contact_path(item["id"]), method: 'put', class: '') do |f| %>
                  <div class="form-group text-left">
                    <%= f.label :name  %><br>
                    <%= f.text_field :name, class: "form-control", placeholder: 'Nombre', value: item["name"] %>
                  </div>
                  <div class="form-group text-left">
                    <%= f.label :surname  %><br>
                    <%= f.text_field :surname, class: "form-control", placeholder: 'Apellidos', value: item["surname"] %>
                  </div>
                  <div class="form-group text-left">
                    <%= f.label :phone  %><br>
                    <%= f.text_field :phone, class: "form-control", placeholder: 'Tlf Principal', value: item["phone"] %>
                  </div>
                  <div class="form-group text-left">
                    <%= f.label :email  %><br>
                    <%= f.text_field :email, class: "form-control", placeholder: 'Nombre', value: item["email"] %>
                  </div>
                  <div class="form-group text-left">
                    <%= f.label :avatar  %><br>
                    <%= f.file_field :avatar %>
                  </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('common.cancel') %></button>
                    <%= f.submit  'Aceptar' ,class: " btn btn-primary"%>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>


      <!-- Modal editar contacto-->
      <div class="modal fade" id="newPhone<%= item["id"] %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Nuevo Telf para (<%= item["id"] %>): <%= item["name"].to_s %> <%= item["surname"].to_s %></h4>
            </div>
            <div class="modal-body">
              <%= form_for(:phone, url: contact_create_phone_path(item["id"],phone["id"]), class: '') do |f| %>
                  <div class="form-group text-left">
                    <%= f.label :number  %><br>
                    <%= f.text_field :number, class: "form-control", placeholder: 'número' %>
                  </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('common.cancel') %></button>
                    <%= f.submit  'Aceptar' ,class: " btn btn-primary"%>
                  </div>
              <% end %>
              </div>
        </div>
      </div>
      </div>




  <% end %>
  </tbody>
</table>
<br/><br/><br/>
<%= @body.inspect %>

CLIENTE/client-contacts/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

CLIENTE/client-contacts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientContacts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  Usuario identificado (token): <%=session[:token]%><br/>
  <% if alert.present? %>
      <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-warning"></i>
        <strong>Atención: </strong>
        <%= alert.html_safe %>
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
      </div>
  <% end %>
  <% if notice.present? %>
      <div class="alert alert-success alert-dismissable">
        <i class="fa fa-thumbs-o-up"></i>
        <strong>Noticia: </strong>
        <%= notice.html_safe %>
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
      </div>
  <% end %>
  <hr/>
  <div class="alert alert-info" role="alert">
    Las acciones tachadas están sin construir en el cliente pero activas en api por falta de tiempo o por ser repetitivas
  </div>
  <table class="table table-bordered table-striped table-hover table-condensed table-responsive">
    <tbody>
    <tr>
      <td>
        <%= link_to "Conseguir token",  new_session_path %>
      </td>
      <td>
        <%= link_to "<strike>Registrar nuevo usuario</strike>".html_safe, "#"%>
      </td>
      <td>
        <%= link_to "Todos mis contactos",  contacts_path %>
      </td>
      <td>
        <%= link_to "<strike>Añadir nuevo contacto</strike>".html_safe, "#"%>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "<strike>Buscar contacto por nombre y/o apellido (puedes dejar name o surname vacios)</strike>".html_safe, "#"%>
      </td>
      <td>
        <%= link_to "<strike>Mostrar un contacto (y sus teléfonos)</strike>".html_safe, "#"%>
      </td>
      <td>

      </td>
      <td>
        <%= link_to "<strike>Eliminar usuario (a si mismo)</strike>".html_safe, '#'%>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to "Modificar usuario", session[:token].present?? edit_user_path(session[:token]): "#" %>
      </td>
      <td>
        <%= link_to 'Cerrar sesión en el cliente (aquí)',  session_path("this"),  method: :delete %>
      </td>
      <td>

      </td>
      <td>

      </td>
    </tr>
    </tbody>
  </table>
  <br/>
    <%= yield %>
  </body>
</html>

CLIENTE/client-contacts/app/views/users/edit.html.erb
<div class = "container">
  <div class="wrapper">
    <%= form_tag  user_path(session[:token]),method: 'put'  do %>
        <h3 class="form-signin-heading">Editar usuario</h3>
        <hr class="colorgraph"><br>

        <input type="text" class="form-control" name="name" placeholder="nombre" required="" value="<%=@body["name"]%>" />
        <input type="text" class="form-control" name="surname" placeholder="apellido" required="" value="<%=@body["surname"]%>"/>
        <input type="text" class="form-control" name="email" placeholder="email" required="" value="<%=@body["email"]%>"/>
        <input type="text" class="form-control" name="phone" placeholder="telefono" required="" value="<%=@body["phone"]%>"/>
        <input type="text" class="form-control" name="password" placeholder="contraseña, puedes dejarla en blanco y no cambiará"/>

        <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="Submit">ACEPTAR</button>
    <%end%>
  </div>
</div>